### ISSUE TITLE
windows 中 `wchar_t` 应该是 UTF-16LE

### ISSUE THREAD

**Issue by Mq-b** [parallel101/cppguidebook#10]
https://parallel101.github.io/cppguidebook/unicode/#_8

按照[微软文档](https://learn.microsoft.com/zh-cn/cpp/cpp/char-wchar-t-char16-t-char32-t?view=msvc-170)自己的说法：

> wchar_t 类型是实现定义的宽字符类型。 在 Microsoft 编译器中，它表示一个 16 位宽字符，用于存储编码为 [**UTF-16LE**](https://stackoverflow.com/questions/36550038/in-utf-16-utf-16be-utf-16le-is-the-endian-of-utf-16-the-computers-endianness) 的 Unicode（Windows 操作系统上的本机字符类型）。

The wchar_t type is an implementation-defined wide character type. In the Microsoft compiler, it represents a 16-bit wide character used to store Unicode encoded as UTF-16LE, the native character type on Windows operating systems.

**Comment by frederick-vs-ja** [comment]
好像没有必要专门强调 UTF-16LE， Windows 上各种标量类型都只有 LE 的实现。
