### ISSUE TITLE
std::make_shared是C++11引入的，C++14引入的是std::make_unique

### ISSUE THREAD

**Issue by Murlocccc** [parallel101/cppguidebook#19]
"现代 C++ 从拒绝 new 开始" - "贴士 2.2"里，描述存在些许错误，如标题所说，C++11就已经引入了std::make_shared
![image](https://github.com/user-attachments/assets/63f4fb2a-8736-42bf-945f-76bfa9eb7283)

**Comment by archibate** [comment]
感谢提醒，已修复，但我必须指出，C++14才引入了make_unique，总的来说还是C++14开始才出现的用法，此前的教材和项目几乎都在用new这种落后的构造智能指针的方法。
