### ISSUE TITLE
为什么说unicode 兼容 ASCII、Latin-1 

### ISSUE THREAD

**Issue by CrossroadW** [parallel101/cppguidebook#20]
https://github.com/parallel101/cppguidebook/blob/a286f4dae9a904b979733de3910ea3438c9a8557/docs/unicode.md?plain=1#L48
utf8 utf16 utf32 不是只兼容ASCII 吗？Latin-1中128-255如何兼容的呢？

**Comment by archibate** [comment]
unicode是字符集，utf8是编码格式
而ascii，latin1既是字符集又是编码格式
字符集只是数字的对应
在字符集的语境下，unicode字符集的低0-255是和latin-1完全相同的
只不过是utf8这种编码方式，会把128-255用来多字节编码
wendous管utf16le叫unicode是极端错误的历史遗留问题，unicode就是字符集，并没有规定编码格式
因此，你确实可以把latin1的char强转为utf16或32的wchar_t来处理，因为是按值强转(需要字符集兼容)，而不是按指针(需要编码格式兼容)











无法顺畅的大口呼吸，是活着的最好证明

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月9日(周五) 中午12:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [parallel101/cppguidebook] 为什么说unicode 兼容 ASCII、Latin-1  (Issue #20)




 
https://github.com/parallel101/cppguidebook/blob/a286f4dae9a904b979733de3910ea3438c9a8557/docs/unicode.md?plain=1#L48
 utf8 utf16 utf32 不是只兼容ASCII 吗？Latin-1中128-255如何兼容的呢？

**Comment by frederick-vs-ja** [comment]
这里指的是码位的数值相同。

一个例子是如果 `s` 是存储 Latin-1 编码的字符串的 `std::string` 值，则  `s | std::ranges::to<std::u16string>()` 与 `s | std::ranges::to<std::u32string>()` 能直接得到转换到 UTF16/UTF-32 的正确结果，而不需要专门的转码算法。

**Comment by archibate** [comment]
对的！











无法顺畅的大口呼吸，是活着的最好证明

---原始邮件---
发件人: "A. ***@***.***&gt;
发送时间: 2024年8月12日(周一) 下午5:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [parallel101/cppguidebook] 为什么说unicode 兼容 ASCII、Latin-1  (Issue #20)




 
这里指的是码位的数值相同。
 
一个例子是如果 s 是存储 Latin-1 编码的字符串的 std::string 值，则  s | std::ranges::to<std::u16string&gt;() 与 s | std::ranges::to<std::u32string&gt;() 能直接得到转换到 UTF16/UTF-32 的正确结果，而不需要专门的转码算法。
