### ISSUE TITLE
前言的小例子中，此变量应该标记为 static

### ISSUE THREAD

**Issue by LEON-REIN** [parallel101/cppguidebook#22]
## 原文
https://github.com/parallel101/cppguidebook/blob/main/docs/index.md#%E4%B8%BE%E4%B8%AA%E4%BE%8B%E5%AD%90
> 但仅仅是回到 C++17，没有 requires 语法，我们只能自己定义一个 trait 类，并运用烦人的 SFINAE 小技巧，检测表达式是否的合法，又臭又长。

```c++
template <class T, class = void>
struct has_foo {
    inline constexpr bool value = false;
};

xxxxxxx
```

## 问题
这里面的 `value` 应该还要为 `static`，否则报错。
测试链接：https://godbolt.org/z/fsr194e91

**Comment by archibate** [comment]
正确的











无法顺畅的大口呼吸，是活着的最好证明

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月13日(周二) 中午1:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [parallel101/cppguidebook] 前言的小例子中，此变量应该标记为 static (Issue #22)




 
原文
 
https://github.com/parallel101/cppguidebook/blob/main/docs/index.md#%E4%B8%BE%E4%B8%AA%E4%BE%8B%E5%AD%90
  
但仅仅是回到 C++17，没有 requires 语法，我们只能自己定义一个 trait 类，并运用烦人的 SFINAE 小技巧，检测表达式是否的合法，又臭又长。
  template <class T, class = void&gt; struct has_foo {     inline constexpr bool value = false; }; xxxxxxx
 
问题
 
这里面的 value 应该还要为 static，否则报错。
 测试链接：https://godbolt.org/z/fsr194e91

**Comment by frederick-vs-ja** [comment]
怎么没合并 PR 就把 issue 关了？

**Comment by LEON-REIN** [comment]
> 怎么没合并 PR 就把 issue 关了？

哎呀手快了， Reopening...
