### ISSUE TITLE
让虚函数再次伟大一节中存在笔误

### ISSUE THREAD

**Issue by Noob-Bob** [parallel101/cppguidebook#27]
### 原文
把 ??? 部分用一个虚函数顶替：
```c++
struct Reducer {
    virtual int init() = 0;
    virtual int add(int a, int b) = 0;
};

int reduce(vector<int> v, Reducer *reducer) {
    int res = reducer.init();
    for (int i = 0; i < v.size(); i++) {
        res = reducer.add(res, v[i]);
    }
    return res;
}
```
### 笔误
`reduce`函数的for循环中通过指针`reducer`调用`add`应使用`->`而非`.`, 后续的代码段也应作必要改正

**Comment by archibate** [comment]
这不赶紧开个pr











无法顺畅的大口呼吸，是活着的最好证明

---原始邮件---
发件人: "Xuecheng ***@***.***&gt;
发送时间: 2024年8月15日(周四) 中午1:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [parallel101/cppguidebook] 让虚函数再次伟大一节中存在笔误 (Issue #27)




 
原文
 
把 ??? 部分用一个虚函数顶替：
 struct Reducer {     virtual int init() = 0;     virtual int add(int a, int b) = 0; }; int reduce(vector<int&gt; v, Reducer *reducer) {     int res = reducer.init();     for (int i = 0; i < v.size(); i++) {         res = reducer.add(res, v[i]);     }     return res; }
 
笔误
 
reduce函数的for循环中通过指针reducer调用add应使用-&gt;而非., 后续的代码段也应作必要改正
