### ISSUE TITLE
「operator() 很有迷惑性」一节的部分代码遗漏了参数

### ISSUE THREAD

**Issue by johnsmith2078** [parallel101/cppguidebook#39]
**具体是如下部分：**

我建议你自己去 https://cppinsights.io 这个解构语法糖的工具网站动动手试试看：
```cpp
auto lambda = [] (int a) {
    return a + 1;
};
int ret = lambda();
```
实际被编译器翻译成：
```cpp
struct Lambda {
    int operator() (int a) const {
        return a + 1;
    }
};
Lambda lambda;
int ret = lambda.operator() ();
```
而捕获了变量的：
```cpp
int x = 4;
auto lambda = [&x] (int a) {
    return a + x;
};
int ret = lambda();
```
实际被编译器翻译成：
```cpp
struct Lambda {
    int &x;

    Lambda(int &x_) : x(x_) {}

    int operator() (int a) const {
        return a + 1;
    }
};
int x = 4;
Lambda lambda(x);
int ret = lambda.operator() ();
```

**以上四段代码中最后一行的函数调用，都遗漏了实际的int参数**

https://godbolt.org/z/x16nT93ha

**Comment by archibate** [comment]
漏改了！这不帮小彭老师pr一下











无法顺畅的大口呼吸，是活着的最好证明

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月6日(周五) 下午3:38
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [parallel101/cppguidebook] 「operator() 很有迷惑性」一节的部分代码遗漏了参数 (Issue #39)




 
具体是如下部分：
 
我建议你自己去 https://cppinsights.io 这个解构语法糖的工具网站动动手试试看：
 auto lambda = [] (int a) {     return a + 1; }; int ret = lambda();
 
实际被编译器翻译成：
 struct Lambda {     int operator() (int a) const {         return a + 1;     } }; Lambda lambda; int ret = lambda.operator() ();
 
而捕获了变量的：
 int x = 4; auto lambda = [&amp;x] (int a) {     return a + x; }; int ret = lambda();
 
实际被编译器翻译成：
 struct Lambda {     int &amp;x;     Lambda(int &amp;x_) : x(x_) {}     int operator() (int a) const {         return a + 1;     } }; int x = 4; Lambda lambda(x); int ret = lambda.operator() ();
 
以上四段代码中最后一行的函数调用，都遗漏了实际的int参数
 
https://godbolt.org/z/x16nT93ha
