### ISSUE TITLE
小彭老师带你学函数式编程，斜体字多加了一个*（可能是加粗打掉了？）

### ISSUE THREAD

**Issue by z0l0y** [parallel101/cppguidebook#45]
![image](https://github.com/user-attachments/assets/8c840c15-8a73-410f-8b42-5268504311b5)

**Comment by archibate** [comment]
以后看到这种小问题，直接提交pr吧

**Comment by z0l0y** [comment]
OK，我把这章看完了就直接提个pr过去

**Comment by archibate** [comment]
已修复
