### ISSUE TITLE
有返回值函数（除了特殊的）不写 return 是未定义行为

### ISSUE THREAD

**Issue by Mq-b** [parallel101/cppguidebook#5]
[原文](https://142857.red/book/functions/)：

> 对于有返回值的函数，必须写 return 语句，否则程序出错。

“*出错*” 太泛指，按照通常的理解是非良构，编译错误...，然而这是未定义行为。

> 如果控制流抵达 main 函数和特定[协程](https://zh.cppreference.com/w/cpp/language/coroutines) (C++20 起)以外的有返回值的函数的结尾却没有 return 语句，那么[**行为未定义**](https://zh.cppreference.com/w/cpp/language/ub)。

虽然几乎所有编译器都会检查这个未定义行为，并大概率会产生一个编译错误... 

建议可以直接改为：

> - 对于有返回值的函数，必须写 return 语句，否则行为未定义。

然后再可以再补充稍微聊一下未定义行为的事情。

**C++ 就是事情多**，这个“*必须*”，也要打一个引号，可以直接说还有这两个例外（main 和协程），也可以放到补充里。

本仓库在 [main 函数的返回值](https://142857.red/book/helloworld/#main_1)一节中并没有提到可以省略 return 的事情，或许也可以直接在那里进行补充。

> main 函数的函数体不需要包含 [return 语句](https://zh.cppreference.com/w/cpp/language/return)：当控制达到 main 函数体的末尾而未遇到返回语句时，它的效果是执行 return 0;

---

这些改进并不会让描述变得复杂，只不过是严谨了一些，其实只需要稍微提一下有这些东西，可以后续再详细描述。

**Comment by archibate** [comment]
已修复，并加了之前写的未定义行为列表。

**Comment by frederick-vs-ja** [comment]
目前好像还没开始写协程。我试下补充 `main` 函数中 `return` 的情况，补充完后应该可以关闭此 issue 了。

**Comment by Mq-b** [comment]
小彭其实已经改了，不知道聚聚还想补充什么呢

> 目前好像还没开始写协程。我试下补充 `main` 函数中 `return` 的情况，补充完后应该可以关闭此 issue 了。
