### ISSUE TITLE
小彭老师的交流群

### ISSUE THREAD

**Issue by Oxygen1a1** [parallel101/cppguidebook#54]
求一下小鹏老师的微信C++交流群

**Comment by archibate** [comment]
加janicehasadream











无法顺畅的大口呼吸，是活着的最好证明

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月12日(周六) 下午5:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [parallel101/cppguidebook] 小彭老师的交流群 (Issue #54)




 
求一下小鹏老师的微信C++交流群
