### ISSUE TITLE
现代化的API设计指南章节问题

### ISSUE THREAD

**Issue by fengchen321** [parallel101/cppguidebook#55]
subspan的实现最后应该return Span(data + start, length);

**Comment by fengchen321** [comment]
std::optional<int> parseInt(std::string_view sv) {
    int value;
    auto result = std::from_chars(sv.data(), sv.data() + sv.size(), value); // 原本位置这行写错了
    if (result.ec == std::errc())
        return value;
    else
        return std::nullopt;
}

**Comment by fengchen321** [comment]
封装file_read时，numElements 获取问题，fread应该改为 .numElements = (n == 0) ? std::nullopt : std::optional<size_t>(n)。
fopen封装，第二个参数是const char*, 应该加上c_str(): modeLut.at(mode).c_str()

**Comment by archibate** [comment]
感谢指出！已修复
